# Create a DataFrame

Learn how to create a DataFrame by using different data structures.

Although we mostly read data from an external file, Pandas also allows for creating your own <font color ='red'>DataFrame</font>.

# 1. Python dictionary
One of the most commonly used methods to do so is with a Python dictionary. We just pass a dictionary to the DataFrame constructor.

In [1]:
import pandas as pd

df = pd.DataFrame({
  "Names": ["Jane", "John", "Matt", "Ashley"],
  "Ages": [26, 24, 28, 25],
  "Score": [91.2, 94.1, 89.5, 92.3]
})

print(df)

    Names  Ages  Score
0    Jane    26   91.2
1    John    24   94.1
2    Matt    28   89.5
3  Ashley    25   92.3


# 2.Two-dimensional array

<font color ='red'>DataFrame</font> is a two-dimensional data structure that consists of rows and columns. Thus, we can convert a two-dimensional array into a <font color ='red'>DataFrame</font>. For instance, the <font color ='red'>DataFrame</font> constructor accepts NumPy arrays.

The code below creates a <font color ='red'>DataFrame</font> using a NumPy array. By default, column names are assigned integer index, but we can change it using the <font color ='red'>columns</font> parameter.

In [6]:
import numpy as np
import pandas as pd

arr = np.random.randint(1, 10, size=(3,5))

# df = pd.DataFrame(arr, columns=["A","B","C","D","E"])

print(arr)

[[5 1 4 4 4]
 [7 4 7 7 7]
 [3 9 7 7 6]]


In [7]:
df = pd.DataFrame(arr, columns=["A","B","C","D","E"])

print(df)

   A  B  C  D  E
0  5  1  4  4  4
1  7  4  7  7  7
2  3  9  7  7  6


We’ve seen how to create a <font color ='red'>DataFrame</font>  using <u>Python dictionaries and NumPy arrays</u>.